<a href="https://colab.research.google.com/github/Monipoo0904/iCouldHaveDied/blob/main/Mreed_Excercise1a_SVM_440.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import fetch_openml
#load mice protein dataset from OpenML
mice = fetch_openml(name='miceprotein', version=4, as_frame=True)
list(mice.frame.columns)
print(mice.details)
mice.frame.describe()


# Import required libraries
import numpy as np
import sklearn
from sklearn.neural_network import MLPClassifier


# Import model to divide data into training and testing sets
from sklearn.model_selection import train_test_split


target_column = ['class']
#derive the list of predictor column id's
predictors = list(set(list(mice.frame.columns))-set(target_column))
#standardize the predictors by dividing by the maximum
mice.frame[predictors] = mice.frame[predictors]/mice.frame[predictors].max()
#provide summary statistics for the dataframe
mice.frame.describe().transpose()

#Get rid of any rows with NA's
mice.frame = mice.frame.dropna()

#the input data
X = mice.frame[predictors].values
#the output data
y = mice.frame[target_column].values

#we encode target classes from strings to numbers as neural networks cannot require all numerical inputs and outputs
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

#divide data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
print(X_train.shape); print(X_test.shape)

from sklearn import svm

svm_model = svm.SVC(decision_function_shape='ovo')
svm_model.fit(X_train, y_train)

#We predict the training set
predict_train = svm_model.predict(X_train)
#we predict the test set
predict_test = svm_model.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix

print('Training accuracy')
#we report the confusion matrix for the training set
print(confusion_matrix(y_train,predict_train))
#we report various accuracy statistics for the training set
print(classification_report(y_train,predict_train))

print('Testing accuracy')
#we report the confusion matrix for the test set
print(confusion_matrix(y_test,predict_test))
#we report various accuracy statistics for the test set
print(classification_report(y_test,predict_test))



{'id': '40966', 'name': 'MiceProtein', 'version': '4', 'description_version': '1', 'format': 'ARFF', 'upload_date': '2017-11-08T16:00:15', 'licence': 'Public', 'url': 'https://api.openml.org/data/v1/download/17928620/MiceProtein.arff', 'parquet_url': 'https://data.openml.org/datasets/0004/40966/dataset_40966.pq', 'file_id': '17928620', 'default_target_attribute': 'class', 'row_id_attribute': 'MouseID', 'ignore_attribute': ['Genotype', 'Treatment', 'Behavior'], 'tag': ['Biology', 'Data Science', 'Health', 'OpenML-CC18', 'Research', 'study_135', 'study_98', 'study_99'], 'visibility': 'public', 'minio_url': 'https://data.openml.org/datasets/0004/40966/dataset_40966.pq', 'status': 'active', 'processing_date': '2018-10-04 00:49:58', 'md5_checksum': '3c479a6885bfa0438971388283a1ce32'}
(386, 77)
(166, 77)
Training accuracy
[[28  0  0  0  0  0  0  0]
 [ 0 54  0  0  0  0  0  0]
 [ 0  0 43  0  0  0  0  0]
 [ 0  0  0 49  0  0  0  0]
 [ 0  0  0  0 63  0  0  0]
 [ 0  0  0  0  0 57  0  0]
 [ 0  0  2

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
